# 
# Copyright 1991-1998 by Open Software Foundation, Inc. 
#              All Rights Reserved 
#  
# Permission to use, copy, modify, and distribute this software and 
# its documentation for any purpose and without fee is hereby granted, 
# provided that the above copyright notice appears in all copies and 
# that both the copyright notice and this permission notice appear in 
# supporting documentation. 
#  
# OSF DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE 
# INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS 
# FOR A PARTICULAR PURPOSE. 
#  
# IN NO EVENT SHALL OSF BE LIABLE FOR ANY SPECIAL, INDIRECT, OR 
# CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
# LOSS OF USE, DATA OR PROFITS, WHETHER IN ACTION OF CONTRACT, 
# NEGLIGENCE, OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION 
# WITH THE USE OR PERFORMANCE OF THIS SOFTWARE. 
# 
# 
# MkLinux


INCLUDES = arp.h bid.h bidctl.h blast.h bootp.h censustaker.h chan.h\
	   dgram.h dtime.h eth.h eth_host.h heartbeat.h icmp.h ip.h ip_host.h\
	   mselect.h membership.h mship.h panning.h select.h sequencer.h\
	   sim.h tcp.h udp.h vcache.h vchan.h vdrop.h vmux.h vnet.h vsize.h

ILIST                   = ${INCLUDES}
IDIR                    = /usr/comm/xkern/include/prot/
IMODE                   = 644

.include <${RULES_MK}>
